project:
  output-dir: _book
  render:
    - slides/index.qmd
    - slides/slides.qmd
    - slides/suppl_slides.qmd

format:
  clean-revealjs:
    smaller: true

html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" 




